//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSCteNfe
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.natura.net/CteNfse", ConfigurationName="WSCteNfe.SI_ProcessaCteNfse_Sync")]
    public interface SI_ProcessaCteNfse_Sync
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSCteNfe.SI_ProcessaCteNfse_SyncResponse> SI_ProcessaCteNfse_SyncAsync(WSCteNfe.SI_ProcessaCteNfse_SyncRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.natura.net/CteNfse")]
    public partial class DT_EletronicDocumentRequest
    {
        
        private DT_EletronicDocumentRequestDados dadosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_EletronicDocumentRequestDados dados
        {
            get
            {
                return this.dadosField;
            }
            set
            {
                this.dadosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.natura.net/CteNfse")]
    public partial class DT_EletronicDocumentRequestDados
    {
        
        private string numeroTransporteField;
        
        private string codTranspMatrizField;
        
        private string codTranspEmitField;
        
        private string cnpjEmitenteField;
        
        private string cnpjTomadorField;
        
        private DT_EletronicDocumentRequestDadosDocumentoFiscal[] documentoFiscalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string numeroTransporte
        {
            get
            {
                return this.numeroTransporteField;
            }
            set
            {
                this.numeroTransporteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codTranspMatriz
        {
            get
            {
                return this.codTranspMatrizField;
            }
            set
            {
                this.codTranspMatrizField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codTranspEmit
        {
            get
            {
                return this.codTranspEmitField;
            }
            set
            {
                this.codTranspEmitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string cnpjEmitente
        {
            get
            {
                return this.cnpjEmitenteField;
            }
            set
            {
                this.cnpjEmitenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cnpjTomador
        {
            get
            {
                return this.cnpjTomadorField;
            }
            set
            {
                this.cnpjTomadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("documentoFiscal", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public DT_EletronicDocumentRequestDadosDocumentoFiscal[] documentoFiscal
        {
            get
            {
                return this.documentoFiscalField;
            }
            set
            {
                this.documentoFiscalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.natura.net/CteNfse")]
    public partial class DT_EletronicDocumentRequestDadosDocumentoFiscal
    {
        
        private string numeroField;
        
        private string serieField;
        
        private string modeloField;
        
        private System.DateTime dataEmissaoField;
        
        private string origemField;
        
        private string destinoField;
        
        private string tipoDocField;
        
        private string valorFreteField;
        
        private string valorImpostosField;
        
        private DT_EletronicDocumentRequestDadosDocumentoFiscalNfse nfseField;
        
        private DT_EletronicDocumentRequestDadosDocumentoFiscalCte cteField;
        
        private DT_EletronicDocumentRequestDadosDocumentoFiscalNotasTransportadas[] notasTransportadasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string numero
        {
            get
            {
                return this.numeroField;
            }
            set
            {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string serie
        {
            get
            {
                return this.serieField;
            }
            set
            {
                this.serieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string modelo
        {
            get
            {
                return this.modeloField;
            }
            set
            {
                this.modeloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=3)]
        public System.DateTime dataEmissao
        {
            get
            {
                return this.dataEmissaoField;
            }
            set
            {
                this.dataEmissaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string origem
        {
            get
            {
                return this.origemField;
            }
            set
            {
                this.origemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string destino
        {
            get
            {
                return this.destinoField;
            }
            set
            {
                this.destinoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string tipoDoc
        {
            get
            {
                return this.tipoDocField;
            }
            set
            {
                this.tipoDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string valorFrete
        {
            get
            {
                return this.valorFreteField;
            }
            set
            {
                this.valorFreteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string valorImpostos
        {
            get
            {
                return this.valorImpostosField;
            }
            set
            {
                this.valorImpostosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public DT_EletronicDocumentRequestDadosDocumentoFiscalNfse nfse
        {
            get
            {
                return this.nfseField;
            }
            set
            {
                this.nfseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public DT_EletronicDocumentRequestDadosDocumentoFiscalCte cte
        {
            get
            {
                return this.cteField;
            }
            set
            {
                this.cteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("notasTransportadas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public DT_EletronicDocumentRequestDadosDocumentoFiscalNotasTransportadas[] notasTransportadas
        {
            get
            {
                return this.notasTransportadasField;
            }
            set
            {
                this.notasTransportadasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.natura.net/CteNfse")]
    public partial class DT_EletronicDocumentRequestDadosDocumentoFiscalNfse
    {
        
        private string retencaoField;
        
        private string aliqISSField;
        
        private string baseISSField;
        
        private string valorISSField;
        
        private string aliqPISField;
        
        private string basePISField;
        
        private string valorPISField;
        
        private string aliqCOFINSField;
        
        private string baseCOFINSField;
        
        private string valorCOFINSField;
        
        private string aliqCSLLField;
        
        private string baseCSLLField;
        
        private string valorCSLLField;
        
        private string aliqIRField;
        
        private string baseIRField;
        
        private string valorIRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string retencao
        {
            get
            {
                return this.retencaoField;
            }
            set
            {
                this.retencaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string aliqISS
        {
            get
            {
                return this.aliqISSField;
            }
            set
            {
                this.aliqISSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string baseISS
        {
            get
            {
                return this.baseISSField;
            }
            set
            {
                this.baseISSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string valorISS
        {
            get
            {
                return this.valorISSField;
            }
            set
            {
                this.valorISSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string aliqPIS
        {
            get
            {
                return this.aliqPISField;
            }
            set
            {
                this.aliqPISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string basePIS
        {
            get
            {
                return this.basePISField;
            }
            set
            {
                this.basePISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string valorPIS
        {
            get
            {
                return this.valorPISField;
            }
            set
            {
                this.valorPISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string aliqCOFINS
        {
            get
            {
                return this.aliqCOFINSField;
            }
            set
            {
                this.aliqCOFINSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string baseCOFINS
        {
            get
            {
                return this.baseCOFINSField;
            }
            set
            {
                this.baseCOFINSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string valorCOFINS
        {
            get
            {
                return this.valorCOFINSField;
            }
            set
            {
                this.valorCOFINSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string aliqCSLL
        {
            get
            {
                return this.aliqCSLLField;
            }
            set
            {
                this.aliqCSLLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string baseCSLL
        {
            get
            {
                return this.baseCSLLField;
            }
            set
            {
                this.baseCSLLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string valorCSLL
        {
            get
            {
                return this.valorCSLLField;
            }
            set
            {
                this.valorCSLLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string aliqIR
        {
            get
            {
                return this.aliqIRField;
            }
            set
            {
                this.aliqIRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string baseIR
        {
            get
            {
                return this.baseIRField;
            }
            set
            {
                this.baseIRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string valorIR
        {
            get
            {
                return this.valorIRField;
            }
            set
            {
                this.valorIRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.natura.net/CteNfse")]
    public partial class DT_EletronicDocumentRequestDadosDocumentoFiscalCte
    {
        
        private string chaveCTeField;
        
        private string xmlCTeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string chaveCTe
        {
            get
            {
                return this.chaveCTeField;
            }
            set
            {
                this.chaveCTeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string xmlCTe
        {
            get
            {
                return this.xmlCTeField;
            }
            set
            {
                this.xmlCTeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.natura.net/CteNfse")]
    public partial class DT_EletronicDocumentRequestDadosDocumentoFiscalNotasTransportadas
    {
        
        private string chaveNFeField;
        
        private System.DateTime dataEmissaoField;
        
        private bool dataEmissaoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string chaveNFe
        {
            get
            {
                return this.chaveNFeField;
            }
            set
            {
                this.chaveNFeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=1)]
        public System.DateTime dataEmissao
        {
            get
            {
                return this.dataEmissaoField;
            }
            set
            {
                this.dataEmissaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataEmissaoSpecified
        {
            get
            {
                return this.dataEmissaoFieldSpecified;
            }
            set
            {
                this.dataEmissaoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.natura.net/CteNfse")]
    public partial class DT_EletronicDocumentResponseDados
    {
        
        private string typeField;
        
        private string idField;
        
        private string numberField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=2)]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ProcessaCteNfse_SyncRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.natura.net/CteNfse", Order=0)]
        public WSCteNfe.DT_EletronicDocumentRequest MT_EletronicDocumentRequest;
        
        public SI_ProcessaCteNfse_SyncRequest()
        {
        }
        
        public SI_ProcessaCteNfse_SyncRequest(WSCteNfe.DT_EletronicDocumentRequest MT_EletronicDocumentRequest)
        {
            this.MT_EletronicDocumentRequest = MT_EletronicDocumentRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ProcessaCteNfse_SyncResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.natura.net/CteNfse", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dados", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WSCteNfe.DT_EletronicDocumentResponseDados[] MT_EletronicDocumentResponse;
        
        public SI_ProcessaCteNfse_SyncResponse()
        {
        }
        
        public SI_ProcessaCteNfse_SyncResponse(WSCteNfe.DT_EletronicDocumentResponseDados[] MT_EletronicDocumentResponse)
        {
            this.MT_EletronicDocumentResponse = MT_EletronicDocumentResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface SI_ProcessaCteNfse_SyncChannel : WSCteNfe.SI_ProcessaCteNfse_Sync, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SI_ProcessaCteNfse_SyncClient : System.ServiceModel.ClientBase<WSCteNfe.SI_ProcessaCteNfse_Sync>, WSCteNfe.SI_ProcessaCteNfse_Sync
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SI_ProcessaCteNfse_SyncClient(EndpointConfiguration endpointConfiguration) : 
                base(SI_ProcessaCteNfse_SyncClient.GetBindingForEndpoint(endpointConfiguration), SI_ProcessaCteNfse_SyncClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_ProcessaCteNfse_SyncClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SI_ProcessaCteNfse_SyncClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_ProcessaCteNfse_SyncClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SI_ProcessaCteNfse_SyncClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_ProcessaCteNfse_SyncClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSCteNfe.SI_ProcessaCteNfse_SyncResponse> WSCteNfe.SI_ProcessaCteNfse_Sync.SI_ProcessaCteNfse_SyncAsync(WSCteNfe.SI_ProcessaCteNfse_SyncRequest request)
        {
            return base.Channel.SI_ProcessaCteNfse_SyncAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSCteNfe.SI_ProcessaCteNfse_SyncResponse> SI_ProcessaCteNfse_SyncAsync(WSCteNfe.DT_EletronicDocumentRequest MT_EletronicDocumentRequest)
        {
            WSCteNfe.SI_ProcessaCteNfse_SyncRequest inValue = new WSCteNfe.SI_ProcessaCteNfse_SyncRequest();
            inValue.MT_EletronicDocumentRequest = MT_EletronicDocumentRequest;
            return ((WSCteNfe.SI_ProcessaCteNfse_Sync)(this)).SI_ProcessaCteNfse_SyncAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            System.ServiceModel.EndpointAddress AcessoWsProducaoMock = new System.ServiceModel.EndpointAddress("http://localhost:8088/mockSI_ProcessaCteNfse_SyncBinding");
            System.ServiceModel.EndpointAddress AcessoWsProducao = new System.ServiceModel.EndpointAddress("http://aslx251br.natura.com.br:50200/XISOAPAdapter/MessageServlet?senderParty=&se" +
                    "nderService=TRANSPORTES&receiverParty=&receiverService=&interface=SI_ProcessaCte" +
                    "Nfse_Sync&interfaceNamespace=http%3A%2F%2Fwww.natura.net%2FCteNfse");

            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                return AcessoWsProducaoMock;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                return AcessoWsProducaoMock;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HTTP_Port,
            
            HTTPS_Port,
        }

    }
}
